### ISSUE TITLE
"password_extractor" generate wrong answere

### ISSUE THREAD

**Issue by octopus-one** [HiMyNameIsIlNano/vpnbook#1] opened 2019-08-03 08:49 UTC
I have just tested and answers from vpnbook isn't same as script returns. as you can se difference is "e" in middle of password.

Script aswere:
+ pwd=r6QN92
+ echo r6QN92

Vpnbook
Password: r6QeN92

https://www.snbforums.com/threads/free-or-very-cheap-openvpn-services-with-multiple-us-locations.57250/page-2#post-507962

**Comment by HiMyNameIsIlNano** [comment] 2019-08-03 11:52
@octopus-one: I cannot reproduce it. I get the correct password. Can you please tell me what the version and which OS  you are using and what shell is it the one you have used to run the `password_extractor`?

**Comment by octopus-one** [comment] 2019-08-03 13:10
I'm using inside my router and execute with: /jffs/scripts/vpnbook.sh
If I modify this line, remove: | tr -d '[:space:]'
pwd=$(cat ${output_file} | grep -Eo '"WordText":.*?[^\\]",' | awk -F':' '{print $2}' | awk -F',' '{print $1}' | tr -d \")
it's working fine. Removed delete space command !!!???

octopus@RT-AC68U:/tmp/home/root# /jffs/scripts/vpnbook.sh
+ vpnbook_folder=/root/.vpnbook
+ vpnbook_base_url=https://www.vpnbook.com
+ vpnbook_url=https://www.vpnbook.com/freevpn
+ tesseract_service_url=https://api.ocr.space/parse/image
+ date +%s
+ timestamp=1564837621
+ output_file=/tmp/vpnbok_pwd_1564837621.json
+ [  !=  ]
+ curl -s https://www.vpnbook.com/freevpn
+ grep -m2 Password:
+ tail -n1
+ cut -d " -f2
+ pwd_url=password.php?t=0.02290800 1564836494
+ echo Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.02290800 1564836494
Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.02290800 1564836494
+ curl -X POST --header apikey: 5a64d478-9c89-43d8-88e3-c65de9999580 -F url=https://www.vpnbook.com/password.php?t=0.02290800 1564836494 -F language=eng -F isOverlayRequired=true -F FileType=.Auto -F IsCreateSearchablePDF=false -F isSearchablePdfHideTextLayer=true -F scale=true -F detectOrientation=false -F isTable=false https://api.ocr.space/parse/image -o /tmp/vpnbok_pwd_1564837621.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1527  100   471  100  1056    311    697  0:00:01  0:00:01 --:--:--  1014
+ cat /tmp/vpnbok_pwd_1564837621.json
+ awk -F, {print $1}
+ tr -d "
+ grep -Eo "WordText":.*?[^\\]",
+ awk -F: {print $2}
+ tr -d [:space:]
+ pwd=r6QN92
+ echo r6QN92
r6QN92
+ exit 0

**Comment by HiMyNameIsIlNano** [comment] 2019-08-03 18:25
@octopus-one ok, so removing `| tr -d '[:space:]'` made it work. I just want to check what difference can that make, or better said, I just need to recall why I needed it in the first place.

@Edit: I added a new branch for the fix called `improve-pwd-retrieval`. Can you check that out, use the script and post the log file here? The log file is located under `/tmp/vpnbok_pwd_%timestamp%.log`

**Comment by octopus-one** [comment] 2019-08-03 19:40
I have tested and get this results:

Log:
------
---not_trimmed_pwd:r6QeN92---
---pwd:r6QN92---

octopus@RT-AC68U:/tmp/home/root# /jffs/scripts/vpnb.sh
+ vpnbook_folder=/root/.vpnbook
+ vpnbook_base_url=https://www.vpnbook.com
+ vpnbook_url=https://www.vpnbook.com/freevpn
+ tesseract_service_url=https://api.ocr.space/parse/image
+ date +%s
+ timestamp=1564860764
+ output_file=/tmp/vpnbok_pwd_1564860764.json
+ log_file=/tmp/vpnbok_pwd_1564860764.log
+ [  !=  ]
+ curl -s https://www.vpnbook.com/freevpn
+ tail -n1
+ grep -m2 Password:
+ cut -d " -f2
+ pwd_url=password.php?t=0.56943700 1564859636
+ echo Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.56943700 1564859636
Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.56943700 1564859636
+ curl -X POST --header apikey: 5a64d478-9c89-43d8-88e3-c65de9999580 -F url=https://www.vpnbook.com/password.php?t=0.56943700 1564859636 -F language=eng -F isOverlayRequired=true -F FileType=.Auto -F IsCreateSearchablePDF=false -F isSearchablePdfHideTextLayer=true -F scale=true -F detectOrientation=false -F isTable=false https://api.ocr.space/parse/image -o /tmp/vpnbok_pwd_1564860764.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1528  100   472  100  1056    240    539  0:00:01  0:00:01 --:--:--   879
+ ps -ef
+ grep 21778
+ grep -v grep
ps: invalid option -- e
BusyBox v1.25.1 (2019-07-31 13:27:26 EDT) multi-call binary.

Usage: ps 

Show list of processes

	w	Wide output
	T	Show threads
+ current_ps=
+ echo ------
+ cat /tmp/vpnbok_pwd_1564860764.json
+ awk -F, {print $1}
+ grep -Eo "WordText":.*?[^\\]",
+ tr -d "
+ awk -F: {print $2}
+ not_trimmed_pwd=r6QeN92
+ echo ---not_trimmed_pwd:r6QeN92---
+ cat /tmp/vpnbok_pwd_1564860764.json
+ awk -F: {print $2}
+ tr -d [:space:]+ 
awk -F, {print $1}
+ tr -d "
+ grep -Eo "WordText":.*?[^\\]",
+ pwd=r6QN92
+ echo ---pwd:r6QN92---
+ echo r6QeN92
+ exit 0

**Comment by HiMyNameIsIlNano** [comment] 2019-08-03 20:27
@octopus-one Would you be so kind and tell me in which shell you are running the script?

**Comment by octopus-one** [comment] 2019-08-03 20:36
I'm using RMerlin router software and execute with xshell in a -sh script over ssh.

**Comment by HiMyNameIsIlNano** [comment] 2019-08-03 20:56
@octopus-one Ok. There might be a difference in how trim works on our two OSes. I think I am going to try another thing tomorrow for which I might need your help. I hope this won't be a problem for you, but I am going to commit the change tomorrow.

**Comment by HiMyNameIsIlNano** [comment] 2019-08-04 07:16
@octopus-one I pushed a small change. Can you please retest it and tell me if it works?

**Comment by octopus-one** [comment] 2019-08-04 07:24
Just tested and in: vpnbok_pwd_1564903251.json

{"ParsedResults":[{"TextOverlay":{"Lines":[{"Words":[{"WordText":"r6QeN92","Left":3.0,"Top":0.0,"Height":14.0,"Width":62.0}],"MaxHeight":14.0,"MinTop":0.0}],"HasOverlay":true,"Message":"Total lines: 1"},"TextOrientation":"0","FileParseExitCode":1,"ParsedText":"r6QeN92 \r\n","ErrorMessage":"","ErrorDetails":""}],"OCRExitCode":1,"IsErroredOnProcessing":false,"ProcessingTimeInMilliseconds":"1430","SearchablePDFURL":"Searchable PDF not generated as it was not requested."}

=================================================================
octopus@RT-AC68U:/tmp/home/root# /jffs/scripts/vpnb.sh
+ debug_flag=0
+ vpnbook_folder=/root/.vpnbook
+ vpnbook_base_url=https://www.vpnbook.com
+ vpnbook_url=https://www.vpnbook.com/freevpn
+ tesseract_service_url=https://api.ocr.space/parse/image
+ date +%s
+ timestamp=1564903251
+ output_file=/tmp/vpnbok_pwd_1564903251.json
+ log_file=/tmp/vpnbok_pwd_1564903251.log
+ [  !=  ]
+ curl -s https://www.vpnbook.com/freevpn
+ grep -m2 Password:
+ tail -n1
+ cut -d " -f2
+ pwd_url=password.php?t=0.61461800 1564902122
+ echo Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.61461800 1564902122
Retrieving Password at the following URL: https://www.vpnbook.com/password.php?t=0.61461800 1564902122
+ curl -X POST --header apikey: 5a64d478-9c89-43d8-88e3-c65de9999580 -F url=https://www.vpnbook.com/password.php?t=0.61461800 1564902122 -F language=eng -F isOverlayRequired=true -F FileType=.Auto -F IsCreateSearchablePDF=false -F isSearchablePdfHideTextLayer=true -F scale=true -F detectOrientation=false -F isTable=false https://api.ocr.space/parse/image -o /tmp/vpnbok_pwd_1564903251.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1528  100   472  100  1056    214    479  0:00:02  0:00:02 --:--:--   745
+ __extract_pwd /tmp/vpnbok_pwd_1564903251.json
+ local file=/tmp/vpnbok_pwd_1564903251.json
+ cat /tmp/vpnbok_pwd_1564903251.json
+ tr -d [:blank:]
+ grep -Eo "WordText":.*?[^\\]",
+ awk -F, {print $1}
+ awk -F: {print $2}
+ tr -d "
+ local pwd=r6QeN92
+ echo r6QeN92
+ pwd=r6QeN92
+ echo ---pwd:r6QeN92---
---pwd:r6QeN92---
+ exit 0

**Comment by HiMyNameIsIlNano** [comment] 2019-08-04 07:48
@octopus-one Sweet! It seems to have worked. There is obviously a difference between :space and :blank and this seems to have caused the issue. Thank you very much for reporting the problem and the support you provided me with. I merged the fix into master already, so feel free to check that out and use it.

**Comment by octopus-one** [comment] 2019-08-04 07:50
Okey
Thank you to look into it and make a fix.

I change in "old" variant of script from: "space" to "blank" it's working to.

:)

**Comment by HiMyNameIsIlNano** [comment] 2019-08-04 12:33
@octopus-one My pleasure! In addition to that, it was you who found out where the problem was and not me. So, without you I would still be crawling in the dark.

I am going to close this issue.

**Comment by HiMyNameIsIlNano** [comment] 2019-08-04 12:34
Fixed and committed to master branch already.

**Closed as completed by HiMyNameIsIlNano** 2019-08-04 12:34 UTC

**Comment by octopus-one** [comment] 2019-08-04 16:41
Thank you.
Glad to help.
