### ISSUE TITLE
 "password_extractor" generate wrong answere

### ISSUE THREAD

**Issue by octopus-one** [HiMyNameIsIlNano/vpnbook#3] opened 2019-11-26 15:23 UTC
Hi again :)

Get wrong password with this script again. :)

Retrieved password:---2---

**Comment by octopus-one** [comment] 2019-11-26 15:55
{"ParsedResults":[{"TextOverlay":{"Lines":[{"LineText":"2 k3a6râ€¢w","Words":[{"WordText":"2","Left":0.5,"Top":7.0,"Height":10.5,"Width":9.0},{"WordText":"k3a6râ€¢w","Left":10.5,"Top":3.5,"Height":13.5,"Width":52.5}],"MaxHeight":13.5,"MinTop":3.5}],"HasOverlay":true,"Message":"Total lines: 1"},"TextOrientation":"0","FileParseExitCode":1,"ParsedText":"2 k3a6râ€¢w\r\n","ErrorMessage":"","ErrorDetails":""}],"OCRExitCode":1,"IsErroredOnProcessing":false,"ProcessingTimeInMilliseconds":"1075","SearchablePDFURL":"Searchable PDF not generated as it was not requested."}

**Comment by HiMyNameIsIlNano** [comment] 2019-12-01 10:24
Hi @octopus-one,

thanks for reporting the issue and sorry for the delay. It will take a bit before I can fix the issue, but it looks funny to me that, apparently, the grep matches the first WordText item (the one that contains just the symbol '2'). Even if the code would work properly though, the retrieved password would be wrong due to those exotic characters that come from the Ocr service. I have to think on how to solve this issue in a better way, because if the issue is the service, I am afraid there is not much I can do.

Is this problem blocking you, somehow?

Feel free to provide some suggestions.

**Comment by octopus-one** [comment] 2019-12-17 15:05
Hi
No that not bother me, just want to report.
If Ocr service report wrong you can't detecting it right...........
Leave it as it is. Enjoy it when it working which it does most of time.

Regards
octopus-one

**Comment by HiMyNameIsIlNano** [comment] 2020-02-09 08:06
I would close the issue as it seems to be OCR-related and not script related.

**Closed as completed by HiMyNameIsIlNano** 2020-02-09 08:06 UTC
